branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: "jq --arg v '${nextRelease.version}' '.version = $v' src/extension/manifest.json > tmp.json && mv tmp.json src/extension/manifest.json"
  - "@semantic-release/github"

preset: conventionalcommits
tagFormat: "v${version}"
