branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - prepareCmd: "jq --arg v '${nextRelease.version}' '.version = $v' src/extension/manifest.json > tmp.json && mv tmp.json src/extension/manifest.json"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - src/extension/manifest.json
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - "@semantic-release/github"

preset: conventionalcommits
tagFormat: "v${version}"
