name: CI/CD Pipeline

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

env:
  PACKAGE_NAME: dyslexia-friendly.zip
  APP_ID: miepjgfkkommhllbbjaedffcpkncboeo
  PACKAGE_PATH: build/dyslexia-friendly.zip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip xvfb

      # - name: Install Chrome
      #   run: |
      #     wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      #     sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
      #     sudo apt-get update
      #     sudo apt-get install -y google-chrome-stable

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Test
        run: |
          # # Set display environment variable for GUI applications
          # export DISPLAY=:99
          # # Start virtual framebuffer for headless GUI testing (1024x768 resolution, 24-bit color)
          # Xvfb :99 -screen 0 1024x768x24 &
          # # Wait for Xvfb to fully initialize
          # sleep 3
          # # Run tests with virtual display available
          yarn test

      - name: Package
        run: yarn package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/dyslexia-friendly.zip
            build/website
            utils/publish.sh
            firebase.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --project "${{ secrets.FIREBASE_PROJECT }}"

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Publish to Chrome Web Store
        run: utils/publish.sh
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          APP_ID: ${{ env.APP_ID }}
          PACKAGE_PATH: ${{ env.PACKAGE_PATH }}
